version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/mongo:3.4.4
    working_directory: ~/ingestion-api-test
    steps:
      - checkout
      - attach_workspace:
          at: ~/ingestion-api-test
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install pipenv
      - run:
          name: Install Pipenv Reqs
          command: |
            . venv/bin/activate
            pipenv install --system
      - persist_to_workspace:
          root: .
          paths: venv
  
  test:
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/mongo:3.4.4
    working_directory: ~/ingestion-api-test
    steps:
      - checkout
      - attach_workspace:
          at: ~/ingestion-api-test
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nose2

  deploy:
    docker:
      - image: docker:17.12.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build docker file"
          command: |
            docker build -t cidc/ingestion-api:latest .
      - deploy:
          name: "Deploy to docker hub"
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker push cidc/ingestion-api

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
